
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("ingredients").del()
    .then(function () {
      // Inserts seed entries
      return knex("ingredients").insert([
        {id: 1, ingredient_id: 1, name: "Chicken", amount: 1, unit: "pound"},
        {id: 2, ingredient_id: 1, name: "Buffalo sauce", amount: 8, unit: "ounces"},
        {id: 3, ingredient_id: 1, name: "Butter", amount: 4, unit: "tablespoons"},
        {id: 4, ingredient_id: 2, name: "Chicken", amount: 1, unit: "pound"},
        {id: 5, ingredient_id: 2, name: "Jerk Seasoning", amount: 2, unit: "tablespoons"},
        {id: 6, ingredient_id: 3, name: "Tofu", amount: 1, unit: "pound"},
        {id: 7, ingredient_id: 3, name: "Assorted Vegetables", amount: 1, unit: "pound"},
        {id: 8, ingredient_id: 4, name: "Ground Beef", amount: 1, unit: "pound"},
        {id: 9, ingredient_id: 4, name: "Speghetti", amount: 1, unit: "pound"},
        {id: 10, ingredient_id: 4, name: "Tomatoe Sauce", amount: 12, unit: "ounces"},
        {id: 11, ingredient_id: 5, name: "Fried Fish", amount: 1, unit: "pound"},
        {id: 12, ingredient_id: 5, name: "Red Cabbage", amount: 8, unit: "ounces"},
        {id: 13, ingredient_id: 5, name: "Garlic Aoili", amount: 2, unit: "ounces"},
        {id: 14, ingredient_id: 5, name: "Tortilla Shells", amount: 6, unit: "pieces"},
        {id: 15, ingredient_id: 6, name: "Flour", amount: 1, unit: "cup"},
        {id: 16, ingredient_id: 6, name: "Eggs", amount: 4, unit: "eggs"},
        {id: 17, ingredient_id: 6, name: "Nutella", amount: 2, unit: "cups"},
        {id: 18, ingredient_id: 7, name: "Green Cabbage", amount: 1, unit: "pound"},
        {id: 19, ingredient_id: 7, name: "Butter", amount: 2, unit: "tablespoons"},
        {id: 20, ingredient_id: 7, name: "Egg Noodles", amount: 1, unit: "pound"},
        {id: 21, ingredient_id: 7, name: "Lowery's Seasoning", amount: 3, unit: "tablespoons"},
        {id: 22, ingredient_id: 8, name: "Rice", amount: 1, unit: "pound"},
        {id: 23, ingredient_id: 8, name: "Black Beans", amount: 1, unit: "pound"},
        {id: 24, ingredient_id: 8, name: "Olive oil", amount: 2, unit: "tablespoons"},
        {id: 25, ingredient_id: 8, name: "Epazote", amount: 2, unit: "tablespoons"},
        {id: 26, ingredient_id: 9, name: "Kale", amount: 1, unit: "bushel"},
        {id: 27, ingredient_id: 9, name: "Ceasar Dressing", amount: 4, unit: "ounces"},
        {id: 28, ingredient_id: 9, name: "Croutons", amount: 1, unit: "cup"},
        {id: 29, ingredient_id: 9, name: "Paramsean cheese", amount: 2, unit: "ounces"},
        {id: 30, ingredient_id: 10, name: "Chicken", amount: 1, unit: "pound"},
        {id: 31, ingredient_id: 10, name: "Mozzarella", amount: 2, unit: "cups"},
        {id: 32, ingredient_id: 10, name: "Paramsean", amount: 4, unit: "ounces"},
        {id: 33, ingredient_id: 10, name: "Speghetti", amount: 1, unit: "pound"},
        {id: 34, ingredient_id: 10, name: "Tomatoe Sauce", amount: 12, unit: "ounces"},
        {id: 35, ingredient_id: 11, name: "Chicken", amount: 1, unit: "pound"},
        {id: 36, ingredient_id: 11, name: "Kale", amount: 1, unit: "bushel"},
        {id: 37, ingredient_id: 11, name: "Ceasar Dressing", amount: 2, unit: "ounces"},
        {id: 38, ingredient_id: 11, name: "Paramsean", amount: 2, unit: "ounces"},
        {id: 39, ingredient_id: 12, name: "Carrots", amount: 1, unit: "pound"},
        {id: 40, ingredient_id: 12, name: "Ginger", amount: 4, unit: "tablespoons"},
        {id: 41, ingredient_id: 12, name: "Garlic", amount: 1, unit: "clove"},
        {id: 42, ingredient_id: 12, name: "Onions", amount: 1, unit: "whole"},
        {id: 43, ingredient_id: 12, name: "Heavy whipping cream", amount: 2, unit: "ounces"},
        {id: 44, ingredient_id: 13, name: "Chicken wings", amount: 1, unit: "pound"},
        {id: 45, ingredient_id: 13, name: "Buffalo sauce", amount: 2, unit: "cups"},
        {id: 46, ingredient_id: 14, name: "Raw Fish", amount: 12, unit: "strips"},
        {id: 47, ingredient_id: 14, name: "Pickled Ginger", amount: 1, unit: "ounce"},
        {id: 48, ingredient_id: 14, name: "Wasabi", amount: 1, unit: "tablespoon"},
        {id: 49, ingredient_id: 14, name: "Rice", amount: 1, unit: "cup"},
        {id: 50, ingredient_id: 14, name: "Soy Sauce", amount: 2, unit: "ounces"},
        {id: 51, ingredient_id: 15, name: "Chicken", amount: 1, unit: "pound"},
        {id: 52, ingredient_id: 15, name: "Tikka Masala Sauce", amount: 2, unit: "cups"},
        {id: 53, ingredient_id: 15, name: "Rice", amount: 2, unit: "cups"},
        {id: 54, ingredient_id: 15, name: "Pickled Onions", amount: 2, unit: "ounces"},
        {id: 55, ingredient_id: 16, name: "Potatoes", amount: 1, unit: "pound"},
        {id: 56, ingredient_id: 16, name: "Bacon", amount: 1, unit: "pound"},
        {id: 57, ingredient_id: 16, name: "Chives", amount: 2, unit: "ounces"},
        {id: 58, ingredient_id: 16, name: "Shallots", amount: 4, unit: "ounces"},
        {id: 59, ingredient_id: 16, name: "Cheddar Cheese", amount: 1, unit: "cup"},
        {id: 60, ingredient_id: 16, name: "Milk", amount: 2, unit: "cups"},
        {id: 61, ingredient_id: 17, name: "Potatoes", amount: 1, unit: "pound"},
        {id: 62, ingredient_id: 17, name: "Butter", amount: 4, unit: "tablespoons"},
        {id: 63, ingredient_id: 17, name: "Milk", amount: 4, unit: "ounces"},
        {id: 64, ingredient_id: 18, name: "Ground Turkey", amount: 1, unit: "pound"},
        {id: 65, ingredient_id: 18, name: "Potatoes", amount: 1, unit: "pound"},
        {id: 66, ingredient_id: 18, name: "Butter", amount: 1, unit: "cup"},
        {id: 67, ingredient_id: 18, name: "Rosemary", amount: 1, unit: "package"},
        {id: 68, ingredient_id: 18, name: "Onions", amount: 1, unit: "cup"},
        {id: 69, ingredient_id: 18, name: "Mushrooms", amount: 1, unit: "cup"},
        {id: 70, ingredient_id: 18, name: "Flour", amount: 2, unit: "tablespoons"},
        {id: 71, ingredient_id: 18, name: "Garlic", amount: 1, unit: "clove"},
        {id: 72, ingredient_id: 19, name: "Eggs", amount: 4, unit: "eggs"},
        {id: 73, ingredient_id: 19, name: "Bacon", amount: 8, unit: "strips"},
        {id: 74, ingredient_id: 20, name: "Frozen Fruit", amount: 1, unit: "pound"},
        {id: 75, ingredient_id: 20, name: "Orange Juice", amount: 1, unit: "cup"}
      ]);
    });
};
