
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("ingredients").del()
    .then(function () {
      // Inserts seed entries
      return knex("ingredients").insert([
        {id: 1, ingredient_id: 1, name: "Chicken", amount: 1, unit: "pound"},
        {id: 2, ingredient_id: 1, name: "Buffalo sauce", amount: 8, unit: "ounces"},
        {id: 3, ingredient_id: 1, name: "Butter", amount: 4, unit: "tablespoons"},
        {id: 4, ingredient_id: 2, name: "Chicken", amount: 1, unit: "pound"},
        {id: 5, ingredient_id: 2, name: "Jerk Seasoning", amount: 2, unit: "tablespoons"},
        {id: 6, ingredient_id: 3, name: "Tofu", amount: 1, unit: "pound"},
        {id: 7, ingredient_id: 3, name: "Assorted Vegetables", amount: 1, unit: "pound"},
        {id: 8, ingredient_id: 4, name: "Ground Beef", amount: 1, unit: "pound"},
        {id: 9, ingredient_id: 4, name: "Speghetti", amount: 1, unit: "pound"},
        {id: 10, ingredient_id: 4, name: "Tomatoe Sauce", amount: 12, unit: "ounces"},
        {id: 11, ingredient_id: 5, name: "Fried Fish", amount: 1, unit: "pound"},
        {id: 12, ingredient_id: 5, name: "Red Cabbage", amount: 8, unit: "ounces"},
        {id: 13, ingredient_id: 5, name: "Garlic Aoili", amount: 2, unit: "ounces"},
        {id: 14, ingredient_id: 5, name: "Tortilla Shells", amount: 6, unit: "pieces"},
        {id: 15, ingredient_id: , name: , amount: , unit: },
        {id: 16, ingredient_id: , name: , amount: , unit: },
        {id: 17, ingredient_id: , name: , amount: , unit: },
        {id: 18, ingredient_id: 7, name: "Green Cabbage", amount: 1, unit: "pound"},
        {id: 19, ingredient_id: 7, name: "Butter", amount: 2, unit: "tablespoons"},
        {id: 20, ingredient_id: 7, name: "Egg Noodles", amount: 1, unit: "pound"},
        {id: 21, ingredient_id: 7, name: "Lowery's Seasoning", amount: 3, unit: "tablespoons"},
        {id: 22, ingredient_id: 8, name: "Rice", amount: 1, unit: "pound"},
        {id: 23, ingredient_id: 8, name: "Black Beans", amount: 1, unit: "pound"},
        {id: 24, ingredient_id: 8, name: "Olive oil", amount: 2, unit: "tablespoons"},
        {id: 25, ingredient_id: 8, name: "Epazote", amount: 2, unit: "tablespoons"},
        {id: 26, ingredient_id: 9, name: "Kale", amount: 1, unit: "bushel"},
        {id: 27, ingredient_id: 9, name: "Ceasar Dressing", amount: 4, unit: "ounces"},
        {id: 28, ingredient_id: 9, name: "Croutons", amount: 1, unit: "cup"},
        {id: 29, ingredient_id: 9, name: "Paramsean cheese", amount: 2, unit: "ounces"},
        {id: 30, ingredient_id: 10, name: "Chicken", amount: 1, unit: "pound"},
        {id: 31, ingredient_id: 10, name: "Mozzarella", amount: 2, unit: "cups"},
        {id: 32, ingredient_id: 10, name: "Paramsean", amount: 4, unit: "ounces"},
        {id: 33, ingredient_id: 10, name: "Speghetti", amount: 1, unit: "pound"},
        {id: 34, ingredient_id: 10, name: "Tomatoe Sauce", amount: 12, unit: "ounces"},
        {id: 35, ingredient_id: 11, name: "Chicken", amount: 1, unit: "pound"},
        {id: 36, ingredient_id: 11, name: "Kale", amount: 1, unit: "bushel"},
        {id: 37, ingredient_id: 11, name: "Ceasar Dressing", amount: 2, unit: "ounces"},
        {id: 38, ingredient_id: 11, name: "Paramsean", amount: 2, unit: "ounces"},
        {id: 39, ingredient_id: , name: , amount: , unit: },
        {id: 40, ingredient_id: , name: , amount: , unit: },
        {id: 41, ingredient_id: , name: , amount: , unit: },
        {id: 42, ingredient_id: , name: , amount: , unit: },
        {id: 43, ingredient_id: , name: , amount: , unit: },
        {id: 44, ingredient_id: , name: , amount: , unit: },
        {id: 45, ingredient_id: , name: , amount: , unit: },
        {id: 46, ingredient_id: , name: , amount: , unit: },
        {id: 47, ingredient_id: , name: , amount: , unit: },
        {id: 48, ingredient_id: , name: , amount: , unit: },
        {id: 49, ingredient_id: , name: , amount: , unit: },
        {id: 50, ingredient_id: , name: , amount: , unit: },
        {id: 51, ingredient_id: , name: , amount: , unit: },
        {id: 52, ingredient_id: , name: , amount: , unit: },
        {id: 53, ingredient_id: , name: , amount: , unit: },
        {id: 54, ingredient_id: , name: , amount: , unit: },
        {id: 55, ingredient_id: , name: , amount: , unit: },
        {id: 56, ingredient_id: , name: , amount: , unit: },
        {id: 57, ingredient_id: , name: , amount: , unit: },
        {id: 58, ingredient_id: , name: , amount: , unit: },
        {id: 59, ingredient_id: , name: , amount: , unit: },
        {id: 50, ingredient_id: , name: , amount: , unit: },

      ]);
    });
};
